version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - yum install -y jq
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - DOCKER_CREDS=$(aws secretsmanager get-secret-value --secret-id $DOCKER_HUB_SECRET_ARN --region $AWS_REGION | jq -r .SecretString)
      - DOCKER_USER=$(echo $DOCKER_CREDS | jq -r .username)
      - DOCKER_PASS=$(echo $DOCKER_CREDS | jq -r .password)
      - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $DOCKER_HUB_REPO_NAME:latest .
      - docker tag $DOCKER_HUB_REPO_NAME:latest $DOCKER_HUB_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the Docker image to Docker Hub...
      - docker push $DOCKER_HUB_REPO_NAME:latest
      - docker push $DOCKER_HUB_REPO_NAME:$IMAGE_TAG
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $DOCKER_HUB_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
